config/routes.rb
Rails.application.routes.draw do
  devise_for :autors
  get 'home/index'
  root 'home#index'

  resources :articulos
  get 'estaticas/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  belongs_to :autor, optional: true
  has_many :comentarios, dependent: :destroy

  validates :titulo, presence: { :message => "no puede estar vacío" }
  validates :contenido, presence: { :message => "no puede estar vacío" },
            length: {minimum: 50, :message => "es demasiado corto, mínimo 50 caracteres"}

end

app/models/autor.rb
class Autor < ApplicationRecord
  has_many :articulos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController

  def index
  end

  def new
    @boton = "Crear"
    @articulo= current_autor.articulos.build
  end

  def create
    @articulo= current_autor.articulos.build(articulo_params)
    #si guarda bien, le redirigimos
    if @articulo.save
      redirect_to @articulo
    else
      render 'new'#viuelve a mostrar la vista del formulario
    end
  end

  def show
    @articulo = Articulo.find(params[:id])
  end

  def edit
    @articulo = Articulo.find(params[:id])
  end


  def update
    @articulo = Articulo.find(params[:id])
  end

  def destroy
  end

  private
    def articulo_params
      params.require(:articulo).permit(:titulo, :contenido)
    end
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def home
  end

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articulos/_form.html.erb
<%= form_for @articulo do |f| %>

    <% if @articulo.errors.any? %>
        <div id="errors">
          <h2>Se han producido Los siguientes errores: </h2>
          <ul>
            <% @articulo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %><br>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %><br>
    <%= f.submit "#{@boton} Artículo" %>

<% end %>

app/views/articulos/edit.html.erb
<h1>Articulos#edit</h1>
<p>Find me in app/views/articulos/edit.html.erb</p>

app/views/articulos/index.html.erb
<h1>Articulos#index</h1>
<p>Find me in app/views/articulos/index.html.erb</p>

app/views/articulos/new.html.erb
<h1>Articulos#new</h1>

<%= render "form"%>

app/views/articulos/show.html.erb
<h1><%= @articulo.titulo %></h1>
<p>Creado en: <%= @articulo.created_at.strftime("%d-%m-%Y") %></p>
<p><%= @articulo.contenido %></p>

<% if autor_signed_in? %>
    <p><%= link_to "Editar", edit_articulo_path(@articulo)%>
    <p><%= link_to "Eliminar", @articulo, :method => :delete, data: {confirm: "Seguro?"} %>
<% end %>

app/views/estaticas/home.html.erb
<h1>Estaticas#home</h1>
<p>Find me in app/views/estaticas/home.html.erb</p>

app/views/estaticas/index.html.erb
<h1>Estaticas#index</h1>
<p>Find me in app/views/estaticas/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= link_to 'home', root_path %>

      <%= link_to 'iniciar sesión', new_autor_session_path %>
      <%= link_to 'crear cuenta', new_autor_registration_path %>
      <%= link_to 'cerrar sesión', destroy_autor_session_path, method: :delete %>
      <%= link_to 'editar', edit_autor_registration_path %>
      <br>
      <%= yield %>
    </div>
  </body>
</html>